### ISSUE TITLE
Clean Up Log File Output

### ISSUE THREAD

**Issue by kozzy97** [Kinds-of-Intelligence-CFI/animal-ai-unity#28]
The log file that is outputted is very messy, and doesn't contain all information. It should preferably return two things:

1) Log file with system information
2) CSV/JSON(L) with step by step observation information (positions, velocities, reward), that can be used as the basis for returning more information about the environment in future versions.

**Comment by alhasacademy96** [comment]
@kozzy97 wasn't this closed with PR #30 ?

**Comment by kozzy97** [comment]
sorry for the slow reply @alhasacademy96 . No, the log file is still pretty messy and difficult to use, but it now records the data we need from players. We should talk about how to clean up the outputs so its more usable!

**Comment by alhasacademy96** [comment]
Hi @kozzy97, what is the expected output log file format? I think if i got an idea i could get this done quickly.

**Comment by kozzy97** [comment]
Hey @alhasacademy96 !

Currently the log file outputs several system details, which is good for debugging. Then, it outputs some details about the start of the episode and then for each time step it outputs the agent's health, velocity, position, forward, orient, and current score.

I am proposing that this latter information gets output into a CSV file rather than in the log as the following:

|Arena Name | Step | Health | xvelocity | yvelocity | zvelocity | xpos | ypos | zpos |
|------|--------------|-----------|------------| --------------|-----------|------------| --------------|-----------|
|ArenaName1 | 0 | 100      |  0        | 0 | 0 | 20 | 0.5 | 0 |
|ArenaName1 | 1 | 99.9 |  0        | 0 | 0 | 20 | 0.5 | 0 |
|... | ... | ... | ...   | ... | ... | ... | ... | ... |


This is useful because currently the only way to get this information is by parsing the log file, which is quite a burden if you're new to using AAI. If we provide it as a CSV (or JSON(L) or TSV or something like that), then it'll be much easier to use than a log file.

All system information that might be important to debug should still go in the log file, though.

**Comment by alhasacademy96** [comment]
In development now. See notion doc file for details.

**Comment by alhasacademy96** [comment]
BRANCH REF: `feature-cleanup-observations`
