### ISSUE TITLE
Issue spawning items in the E2E tests

### ISSUE THREAD

**Issue by benaslater** [Kinds-of-Intelligence-CFI/animal-ai-unity#43]
**Describe the Bug**
While updating the mlagents version E2E screenshot tests, I noticed the expected screenshots look a bit suspicious for some items. `Bad Goal Multi` and `Hollow Box` were absent and `Ripen Goal` and `Shrink Goal` were half submerged in the arena. We should investigate and make sure these items are working properly (and see if we can fail more loudly next time something like this goes wrong)

**To Reproduce**
Examine current version of screenshot E2E tests screenshots for:
- Bad Goal Multi
- Hollow Box
- Ripen Goal
- Shrink Goal

**Expected Behavior**
For the first two, an item should be visible in the screenshot. For the second two the object should not be submerged in the arena (would be better to throw)

**Desktop (please complete the following information):**
 - OS: Windows
 - Unity Version [I think 2021.3.21f1]

**Screenshots**
![Expected_HollowBox](https://github.com/user-attachments/assets/9438da71-7e11-4f4c-993d-9a3f1402b78c)
![Expected_HollowBox](https://github.com/user-attachments/assets/432b6e9e-89fb-4d2b-8eb1-4da814f4adc1)
![Expected_RipenGoal](https://github.com/user-attachments/assets/480730aa-f98f-49cd-b86f-4c72d8bfabc9)
![Expected_ShrinkGoal](https://github.com/user-attachments/assets/03012cae-c4c1-41e0-a788-25a3fcb5f842)

**Comment by benaslater** [comment]
It when I updated my unity to the latest version it seems the Bad Goal Multi works now, so an intervening change has fixed that (perhaps https://github.com/Kinds-of-Intelligence-CFI/animal-ai-unity/commit/058c71de2e752b67db75f21abadc0c3717fa7d55)

**Comment by alhasacademy96** [comment]
These first teo objects were newly added to the list of acceptable objects (hollow box was meant to be added in 4.1.0 but I forgot to add it then) badgoalmulti is new for 4.2.0 completely. Your recent comment is correct to assume that badgoalmulti works. I'm not sure why the other objects are behaving erratically.

**Comment by alhasacademy96** [comment]
Checked using 4.2.0 build and all objects behave normally (the first frame taken for e2e tests for the ripen goal and shrink goal does not take into account for the physics for these objects, which result in the observed behaviour in this issue). 

Below are confirmations that the ripen goal and shrink goal objects spawn normally (not submerged). The other two objects spawn correctly also: 

<img width="500" alt="Screenshot 2024-10-21 at 22 14 07" src="https://github.com/user-attachments/assets/3c588f75-4ec1-4a0b-a8c8-6f740d8d1596">

<img width="500" alt="Screenshot 2024-10-21 at 22 15 41" src="https://github.com/user-attachments/assets/52f4ee71-3816-4e34-9ede-42aa63957413">

Closing issue as explained.
